# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'converting_ndf_h5_subwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_convert_ndf_to_h5(object):
    def setupUi(self, convert_ndf_to_h5):
        convert_ndf_to_h5.setObjectName("convert_ndf_to_h5")
        convert_ndf_to_h5.resize(790, 460)
        convert_ndf_to_h5.setMinimumSize(QtCore.QSize(790, 460))
        self.verticalLayout = QtWidgets.QVBoxLayout(convert_ndf_to_h5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.select_ndf_folder = QtWidgets.QPushButton(convert_ndf_to_h5)
        self.select_ndf_folder.setMinimumSize(QtCore.QSize(200, 0))
        self.select_ndf_folder.setAutoDefault(False)
        self.select_ndf_folder.setObjectName("select_ndf_folder")
        self.gridLayout.addWidget(self.select_ndf_folder, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(convert_ndf_to_h5)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.transmitter_ids = QtWidgets.QLineEdit(convert_ndf_to_h5)
        self.transmitter_ids.setObjectName("transmitter_ids")
        self.gridLayout.addWidget(self.transmitter_ids, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(convert_ndf_to_h5)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.cores_to_use = QtWidgets.QLineEdit(convert_ndf_to_h5)
        self.cores_to_use.setObjectName("cores_to_use")
        self.gridLayout.addWidget(self.cores_to_use, 4, 1, 1, 1)
        self.ndf_display = QtWidgets.QLineEdit(convert_ndf_to_h5)
        self.ndf_display.setMinimumSize(QtCore.QSize(300, 0))
        self.ndf_display.setObjectName("ndf_display")
        self.gridLayout.addWidget(self.ndf_display, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(convert_ndf_to_h5)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.set_h5_folder = QtWidgets.QPushButton(convert_ndf_to_h5)
        self.set_h5_folder.setMinimumSize(QtCore.QSize(200, 0))
        self.set_h5_folder.setAutoDefault(False)
        self.set_h5_folder.setObjectName("set_h5_folder")
        self.gridLayout.addWidget(self.set_h5_folder, 1, 0, 1, 1)
        self.h5_display = QtWidgets.QLineEdit(convert_ndf_to_h5)
        self.h5_display.setMinimumSize(QtCore.QSize(300, 0))
        self.h5_display.setObjectName("h5_display")
        self.gridLayout.addWidget(self.h5_display, 1, 1, 1, 1)
        self.fs_box = QtWidgets.QLineEdit(convert_ndf_to_h5)
        self.fs_box.setObjectName("fs_box")
        self.gridLayout.addWidget(self.fs_box, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(convert_ndf_to_h5)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(convert_ndf_to_h5)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.checkbox_ndf_glitch_removal = QtWidgets.QCheckBox(convert_ndf_to_h5)
        self.checkbox_ndf_glitch_removal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkbox_ndf_glitch_removal.setText("")
        self.checkbox_ndf_glitch_removal.setChecked(True)
        self.checkbox_ndf_glitch_removal.setObjectName("checkbox_ndf_glitch_removal")
        self.gridLayout.addWidget(self.checkbox_ndf_glitch_removal, 6, 1, 1, 1)
        self.checkbox_ndf_hp_filter_1hz = QtWidgets.QCheckBox(convert_ndf_to_h5)
        self.checkbox_ndf_hp_filter_1hz.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkbox_ndf_hp_filter_1hz.setText("")
        self.checkbox_ndf_hp_filter_1hz.setChecked(True)
        self.checkbox_ndf_hp_filter_1hz.setObjectName("checkbox_ndf_hp_filter_1hz")
        self.gridLayout.addWidget(self.checkbox_ndf_hp_filter_1hz, 7, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.convert_button = QtWidgets.QPushButton(convert_ndf_to_h5)
        self.convert_button.setMinimumSize(QtCore.QSize(180, 0))
        self.convert_button.setAutoDefault(False)
        self.convert_button.setDefault(True)
        self.convert_button.setObjectName("convert_button")
        self.horizontalLayout.addWidget(self.convert_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.hidden_label = QtWidgets.QLabel(convert_ndf_to_h5)
        self.hidden_label.setMinimumSize(QtCore.QSize(600, 0))
        self.hidden_label.setText("")
        self.hidden_label.setObjectName("hidden_label")
        self.verticalLayout.addWidget(self.hidden_label)
        self.progress_bar_label = QtWidgets.QLabel(convert_ndf_to_h5)
        self.progress_bar_label.setObjectName("progress_bar_label")
        self.verticalLayout.addWidget(self.progress_bar_label)
        self.progressBar = QtWidgets.QProgressBar(convert_ndf_to_h5)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.logpath_dsplay = QtWidgets.QLabel(convert_ndf_to_h5)
        self.logpath_dsplay.setMinimumSize(QtCore.QSize(600, 0))
        self.logpath_dsplay.setObjectName("logpath_dsplay")
        self.verticalLayout.addWidget(self.logpath_dsplay)

        self.retranslateUi(convert_ndf_to_h5)
        QtCore.QMetaObject.connectSlotsByName(convert_ndf_to_h5)

    def retranslateUi(self, convert_ndf_to_h5):
        _translate = QtCore.QCoreApplication.translate
        convert_ndf_to_h5.setWindowTitle(_translate("convert_ndf_to_h5", "Dialog"))
        self.select_ndf_folder.setText(_translate("convert_ndf_to_h5", "Choose ndf folder"))
        self.label_2.setText(_translate("convert_ndf_to_h5", "Select transmitter IDs to convert"))
        self.transmitter_ids.setText(_translate("convert_ndf_to_h5", "all"))
        self.label_3.setText(_translate("convert_ndf_to_h5", "Number of CPU cores to use"))
        self.cores_to_use.setText(_translate("convert_ndf_to_h5", "all"))
        self.label.setText(_translate("convert_ndf_to_h5", "Sampling Frequency (Hz)"))
        self.set_h5_folder.setText(_translate("convert_ndf_to_h5", "Choose destination h5 folder"))
        self.fs_box.setText(_translate("convert_ndf_to_h5", "512"))
        self.label_4.setText(_translate("convert_ndf_to_h5", "Glitch removal"))
        self.label_5.setText(_translate("convert_ndf_to_h5", "High pass filter 1 Hz"))
        self.convert_button.setText(_translate("convert_ndf_to_h5", "Convert!"))
        self.progress_bar_label.setText(_translate("convert_ndf_to_h5", "Progress:"))
        self.logpath_dsplay.setText(_translate("convert_ndf_to_h5", "Path to Logfile:"))

