# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'converting_ndf_h5_subwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_convert_ndf_to_h5(object):
    def setupUi(self, convert_ndf_to_h5):
        convert_ndf_to_h5.setObjectName("convert_ndf_to_h5")
        convert_ndf_to_h5.resize(755, 562)
        self.formLayoutWidget = QtWidgets.QWidget(convert_ndf_to_h5)
        self.formLayoutWidget.setGeometry(QtCore.QRect(70, 70, 531, 161))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.ndf_display = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ndf_display.setMinimumSize(QtCore.QSize(300, 0))
        self.ndf_display.setObjectName("ndf_display")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ndf_display)
        self.h5_display = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.h5_display.setMinimumSize(QtCore.QSize(300, 0))
        self.h5_display.setObjectName("h5_display")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.h5_display)
        self.select_ndf_folder = QtWidgets.QPushButton(self.formLayoutWidget)
        self.select_ndf_folder.setMinimumSize(QtCore.QSize(200, 0))
        self.select_ndf_folder.setMaximumSize(QtCore.QSize(170, 16777215))
        self.select_ndf_folder.setObjectName("select_ndf_folder")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.select_ndf_folder)
        self.set_h5_folder = QtWidgets.QPushButton(self.formLayoutWidget)
        self.set_h5_folder.setMinimumSize(QtCore.QSize(200, 0))
        self.set_h5_folder.setMaximumSize(QtCore.QSize(200, 32))
        self.set_h5_folder.setObjectName("set_h5_folder")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.set_h5_folder)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.transmitter_ids = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.transmitter_ids.setObjectName("transmitter_ids")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.transmitter_ids)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.fs_box = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fs_box.setObjectName("fs_box")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fs_box)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.cores_to_use = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.cores_to_use.setObjectName("cores_to_use")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cores_to_use)
        self.progressBar = QtWidgets.QProgressBar(convert_ndf_to_h5)
        self.progressBar.setGeometry(QtCore.QRect(60, 342, 541, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.progress_bar_label = QtWidgets.QLabel(convert_ndf_to_h5)
        self.progress_bar_label.setGeometry(QtCore.QRect(60, 330, 461, 16))
        self.progress_bar_label.setObjectName("progress_bar_label")
        self.convert_button = QtWidgets.QPushButton(convert_ndf_to_h5)
        self.convert_button.setGeometry(QtCore.QRect(280, 250, 110, 32))
        self.convert_button.setObjectName("convert_button")
        self.logpath_dsplay = QtWidgets.QLabel(convert_ndf_to_h5)
        self.logpath_dsplay.setGeometry(QtCore.QRect(60, 380, 600, 16))
        self.logpath_dsplay.setMinimumSize(QtCore.QSize(600, 0))
        self.logpath_dsplay.setObjectName("logpath_dsplay")
        self.hidden_label = QtWidgets.QLabel(convert_ndf_to_h5)
        self.hidden_label.setGeometry(QtCore.QRect(60, 300, 600, 16))
        self.hidden_label.setMinimumSize(QtCore.QSize(600, 0))
        self.hidden_label.setText("")
        self.hidden_label.setObjectName("hidden_label")

        self.retranslateUi(convert_ndf_to_h5)
        QtCore.QMetaObject.connectSlotsByName(convert_ndf_to_h5)

    def retranslateUi(self, convert_ndf_to_h5):
        _translate = QtCore.QCoreApplication.translate
        convert_ndf_to_h5.setWindowTitle(_translate("convert_ndf_to_h5", "Dialog"))
        self.select_ndf_folder.setText(_translate("convert_ndf_to_h5", "Choose ndf folder"))
        self.set_h5_folder.setText(_translate("convert_ndf_to_h5", "Choose destination h5 folder"))
        self.label_2.setText(_translate("convert_ndf_to_h5", "Select transmitter IDs to convert"))
        self.transmitter_ids.setText(_translate("convert_ndf_to_h5", "all"))
        self.label.setText(_translate("convert_ndf_to_h5", "Sampling Frequency (Hz)"))
        self.fs_box.setText(_translate("convert_ndf_to_h5", "512"))
        self.label_3.setText(_translate("convert_ndf_to_h5", "Number of CPU cores to use"))
        self.cores_to_use.setText(_translate("convert_ndf_to_h5", "all"))
        self.progress_bar_label.setText(_translate("convert_ndf_to_h5", "Progress:"))
        self.convert_button.setText(_translate("convert_ndf_to_h5", "Convert!"))
        self.logpath_dsplay.setText(_translate("convert_ndf_to_h5", "Path to Logfile:"))

